name: CI

on:
  - push

jobs:
  lint:
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - 3.8

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version:  ${{ matrix.python-version }}
      - run: pip install flake8
      - run: flake8 setup.py vyos_config_deploy_tool/
